#!/usr/bin/env bash

LOCATION=""
[ ! -d  ~/$LOCATION ] && mkdir ~/$LOCATION
[ ! -d  ~/$LOCATION/$(date +"%y") ] && mkdir ~/$LOCATION/$(date +"%y")
echo "i"$(date +"%d")"#"$(date +"%T") >> ~/$LOCATION/$(date +"%y"/"%m").txt
echo "clocked in at: "$(date)
